### ISSUE TITLE
[Bug] - Manually submitting sessions doesn't update the stats properly

### ISSUE THREAD

**Issue by EmersonPinheiro** [heylinda/heylinda-app#106]
**Before reporting:**
- [ ] The same bug wasn't already reported, i.e. it's not a duplicate (#58)
- [x] This bug is not reported due to an unstable environment

**Steps to reproduce:**

#### Scenario 1
1. Go to the Stats screen.
2. Select a day to manually insert minutes session.
3. Submit 65 minutes.

**Expected behaviour:**
The 'Listened' stat should show '65 minutes' (or 1 hour and 5 minutes).

**Actual behaviour:**
'Listened' stat shows 5 minutes.

#### Scenario 2
1. Go to the Stats screen.
2. Select and submit 10 minutes on 6 different days.

**Expected behaviour:**
The 'Listened' stat should show '60 minutes' (or 1 hour).

**Actual behaviour:**
'Listened' stat shows 0 minutes.

**Smartphone (please complete the following information):**
 - Android Emulator - API 30

**Screenshots/Recording:**

Scenario 1 
![image](https://user-images.githubusercontent.com/22963240/136107343-7d89de2e-f1b1-427c-82af-467da53509a0.png)
![image](https://user-images.githubusercontent.com/22963240/136107363-50050960-b1ed-4679-a244-fefbb7673921.png)

**Comment by watadarkstar** [comment]
@EmersonPinheiro It seems like any value after 60 minutes has this bug

![simulator_screenshot_4FD4F133-8E80-4B49-B9EE-C6A3A1B2D396](https://user-images.githubusercontent.com/3059371/136108401-7ea29486-c22f-43e7-b6f0-3898985d994b.png)
: 

That may give you a clue on how to solve this bug or someone

**Comment by EmersonPinheiro** [comment]
Cool. I can work on this. :)

**Comment by EmersonPinheiro** [comment]
Wich one of the following approaches do you like more for showing the stats to the user?

### 1
![image](https://user-images.githubusercontent.com/22963240/136125394-1d746f71-2dcd-4dae-8eeb-9dd55d3613cc.png)
![image](https://user-images.githubusercontent.com/22963240/136125420-065d9b2b-881f-4e7e-9e1e-f957c9a5caf6.png)
![image](https://user-images.githubusercontent.com/22963240/136125439-b07477ad-77d6-4297-b182-d24d31ffd03d.png)

### 2
![image](https://user-images.githubusercontent.com/22963240/136125457-9541fb8c-8582-457b-acfd-fa1ce6e208af.png)
![image](https://user-images.githubusercontent.com/22963240/136125472-4dec4080-f060-4145-a706-24548bc0cb92.png)
![image](https://user-images.githubusercontent.com/22963240/136125501-a162fdf8-648a-42b7-a147-78972df12e5c.png)
