### ISSUE TITLE
Feature: Make the project more contributor friendly

### ISSUE THREAD

**Issue by orama254** [heylinda/heylinda-app#117]
Greetings @watadarkstar 

as per Github's recommended community standards, the project seems to be missing some items on the checklist namely

 - [x] Code of conduct #120 
 - [x] Contributing guidelines #121 
 
##### screenshot:
![heylinda-app](https://user-images.githubusercontent.com/50571688/136200838-59d86ed6-4a7a-4bd0-b7aa-c29702e1574a.jpg)

I'd be happy to add them to the project if you need any assistance with this

**Comment by watadarkstar** [comment]
@orama254 Thank you for pointing this out! Yes feel free to help 🙏

**Comment by watadarkstar** [comment]
Where did you get that screenshot btw? Can you link me?

**Comment by orama254** [comment]
> Where did you get that screenshot btw? Can you link me?

Sure thing. 

When you navigate to the Insights tab, then the community side panel you will see all the recommendations related to your repository

##### Step 1:
![step-1](https://user-images.githubusercontent.com/50571688/136224163-02acdbcd-9f89-4465-a80d-f15264042412.jpg)
---
---

##### Step 2:
![step-2](https://user-images.githubusercontent.com/50571688/136223697-ffa25316-6dc1-48c1-be5b-fc96b3948dc0.jpg)
