### ISSUE TITLE
Improve Dark Mode

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#13]
- [ ] Dark mode text for tiles should be white 
- [ ] Arrows for calendar should also be white

![simulator_screenshot_CC4242CA-E0F0-4E79-BFD5-D1AE2C6E5799](https://user-images.githubusercontent.com/3059371/127779007-614e12a7-2d08-458b-a582-640c5e312884.png)
![simulator_screenshot_89FF3D1A-A2C9-4744-9D55-4F0DE0C4137B](https://user-images.githubusercontent.com/3059371/127779013-47b109d6-75b6-45b1-ac3a-c76587c3e74f.png)
![simulator_screenshot_634B7DA3-3364-4609-BAD6-4B5461A896AA](https://user-images.githubusercontent.com/3059371/127779029-466e4b4a-e608-4c9a-8f9f-1beceffcda06.png)

**Comment by AliNisarAhmed** [comment]
Hi, I want to contribute, and to get familiar with the project, would like to start with this issue.

**Comment by watadarkstar** [comment]
Sure give it a shot 🙂 Thank you!
