### ISSUE TITLE
Add about screen in settings that has the version number, version code, etc.

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#136]
**Is your feature request related to a problem? Please describe.**
We need an about screen to display the version number, version code, etc.

**Describe the solution you'd like**
Add an about screen in settings that has the version number, version code, etc.

**Additional context**
- See Android about phone screen

**Comment by frubesss** [comment]
Would like to pick this up if that's okay?

**Comment by watadarkstar** [comment]
Sounds good @frubesss thank you!
