### ISSUE TITLE
Domain has been hijacked

### ISSUE THREAD

**Issue by HaigNalbandian** [heylinda/heylinda-app#155]
**Before reporting:**
- [ ] The same bug wasn't already reported, i.e. it's not a duplicate
- [ ] This bug is not reported due to an unstable environment

**Steps to reproduce:**

1. Navigate to https://heylinda.app

**Expected behaviour:**

Site should render

**Actual behaviour:**

Redirected to adware

**Smartphone (please complete the 
following information):**

Any (this is web-based)

**Screenshots/Recording:**

![HeyLinda](https://user-images.githubusercontent.com/6413328/214216353-f77a4480-622c-4c4e-a2e1-9c6e2285e20a.gif)

[HeyLindaHAR.txt](https://github.com/heylinda/heylinda-app/files/10486475/HeyLindaHAR.txt)

**Comment by watadarkstar** [comment]
@HaigNalbandian Thanks for reporting. I'm no longer paying for that domain. So I've changed the domain to https://heylinda.netlify.app 

Please let me know if there are places that I need to update.
