### ISSUE TITLE
[Bug] Calendar background color does not update when Dark mode is toggled

### ISSUE THREAD

**Issue by AliNisarAhmed** [heylinda/heylinda-app#20]
**Before reporting:**
- [x] The same bug wasn't already reported, i.e. it's not a duplicate
- [x] This bug is not reported due to an unstable environment

**Steps to reproduce:**

1. Start with Dark or Light mode in Android settings 
2. Note Calendar background color 
3. Switch to Light/Dark mode
4. Calendar background color remains the same
5. Restarting the app fixes the issue

**Expected behaviour:**

Should reflect the current theme like the rest of the app.

**Actual behaviour:**

Calendar background color is from the old theme.

**Smartphone (please complete the following information):**
 - Pixel 4 XL - Simulator - Android
 - API 30

**Screenshots/Recording:**
![Settings - before](https://user-images.githubusercontent.com/35175560/127956832-51a26aa1-a6d7-4d99-b127-9cd293eac8e2.png)
![Calendar - before](https://user-images.githubusercontent.com/35175560/127956833-59595fa9-c0dc-45a7-83f6-3ef125a948d0.png)
![Settings - after](https://user-images.githubusercontent.com/35175560/127956830-3c1f4c3a-cf81-438b-8f0e-2a2e66f58d85.png)
![App - after](https://user-images.githubusercontent.com/35175560/127956828-994ebd7f-a870-4efc-8751-8da305a1c001.png)

**Comment by AliNisarAhmed** [comment]
@watadarkstar Were you able to reproduce this issue? Before attempting to resolve this, I want to rule out it was not just my simulator doing this (Cannot check on my physical device as Dark mode is not detected on it at all).

**Comment by watadarkstar** [comment]
@AliNisarAhmed Yup I reproduced it. It must be something to do with the library not re-rendering when the props change or something

**Comment by AliNisarAhmed** [comment]
I cannot reproduce this on my device and emulator (no idea why). Clearing myself from assignees so that someone else can take a look at this.
