### ISSUE TITLE
[Bug] Hide the bottom tab navigator on Completed Screen

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#37]
**Before reporting:**
- [x] The same bug wasn't already reported, i.e. it's not a duplicate
- [x] This bug is not reported due to an unstable environment

**Steps to reproduce:**

1. Go to any meditation
2. Complete the meditation
3. See how the bottom tab navigator shows up

**Expected behaviour:**

No bottom tab navigator

**Actual behaviour:**

Bottom tab navigator shows up

**Smartphone (please complete the following information):**
 - Device/OS: iPhone Simulator (all devices)

**Screenshots/Recording:**

![simulator_screenshot_807F5DE9-4C08-4924-9832-D7CA8E8E7DF9](https://user-images.githubusercontent.com/3059371/128092126-208d146b-83ec-4c48-8c70-51408a2ce863.png)

**Comment by AliNisarAhmed** [comment]
I would like to work on this one next.
