### ISSUE TITLE
Improve dark mode for completed screen

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#38]
**Is your feature request related to a problem? Please describe.**
The dark mode for the completed screen doesn't really exist and its kind of bright in my opinion.

**Describe the solution you'd like**
Not really sure what we should do here yet. Please suggest a solution before working on this feature.

**Describe alternatives you've considered**
I considered making the purple darker and the button not white. Leaving the text as white. Thoughts?

**Additional context**

![simulator_screenshot_09FDC64D-394E-4C59-BCE6-B3F326AC31B9](https://user-images.githubusercontent.com/3059371/128094887-b80d0c37-ed2f-48c3-a7b8-af16400b90f3.png)

**Comment by alexandrvicente** [comment]
I think using the default background and making the icon and button purple works better for dark mode, this is what it looked like using a lighter purple (#6f69c9):

![IMG_68F94861CE17-1](https://user-images.githubusercontent.com/609357/130326109-bf4e79a8-ccdd-4e94-9da3-11cb1850a172.jpeg)

**Comment by watadarkstar** [comment]
Yeah that does look better @alexandrvicente !
