### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#4]
Support offline meditations. Figure out how meditations can be downloaded and cached on the device.

**Comment by lsmacedo** [comment]
Any of ideas of what would be a good approach here? Allowing users to manually download the meditations they want, caching audios after they listen or automatically cache them as soon as the app is opened. Or something else you have in mind.

**Comment by watadarkstar** [comment]
@lsmacedo Yeah there might be 2 solutions here:

1. Allow users to download the meditations manually i.e. like Spotify does it
2. Cache the meditations 

I think the solution for this issue could be:

1. Add a download button to the app somewhere
2. Use react-native-fs to download the audio
3. Store the file path using redux-persist 
4. Use the downloaded audio when playing a meditation that has been downloaded
