### ISSUE TITLE
Ability to favourite or save meditations 

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#42]
**Is your feature request related to a problem? Please describe.**
I want to be able to favourite meditations I like and easily access them.

**Describe the solution you'd like**
- Add a favourite / save button
- Add a new screen called Saved
- Add a bottom tab called Saved to access the Saved screen where it would show all your Favourites
- The saved screen should re-use styles and components from the home screen. It should look very similar to the home screen.
- Maybe you can favourite to your own custom lists i.e. When you click Save it asks you if you want to save it to Favourites or create a new list or select another list

**Describe alternatives you've considered**
- It could also be called "Save" instead of Favourites since it will have multiple lists
- Open to other ideas

**Additional context**
<img width="301" alt="Screen Shot 2021-08-04 at 1 30 20 PM" src="https://user-images.githubusercontent.com/3059371/128227038-ca13ed50-04e2-4624-99a2-6557df75c6ee.png">

**Comment by trentmercer** [comment]
Should saving also download the meditation, or should the download button be a separate thing?

**Comment by watadarkstar** [comment]
@trentmercer clearing you as the assigned for this as its been 25 days. Let's have someone else take a look at this issue if you aren't currently working on it :)

**Comment by AliNisarAhmed** [comment]
I can work on this one next.
