### ISSUE TITLE
Cache playback progress 

### ISSUE THREAD

**Issue by trentmercer** [heylinda/heylinda-app#48]
When a meditation is played, the current timestamp of the audio should be cached or saved. That way, when resuming that meditation, the user will start the playback where they left off instead of at the beginning.

**Comment by watadarkstar** [comment]
Does this not happen already? Can you provide more details with reproduction steps? I highly recommend filling out our full bug report template so it's easy for people to understand the bug. I'm not sure I fully understand. Is this when you press pause and then play?

**Comment by trentmercer** [comment]
I should've been more clear, i'll add more detail when I can

to reproduce:

- press play on a meditation. skip forward to a timestamp then pause
- navigate to the home screen, then navigate back to the previous meditation

The meditation starts from time 0:00 instead of wherever we left off

**Comment by watadarkstar** [comment]
Thanks @trentmercer 👍 

Hmmm if you navigate to the home screen and come back I would expect that the meditation starts at 0:00 again because you left. Isn't that what most other meditation apps do? If you navigate away, you have to start over?
