### ISSUE TITLE
Setup Expo EAS (CI/CD)

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#5]
Speak to @watadarkstar to get access to our Expo EAS organization account

**Comment by trentmercer** [comment]
@watadarkstar I can set this up

**Comment by watadarkstar** [comment]
Hey @trentmercer are you on our [Slack](https://join.slack.com/t/heylinda/shared_invite/zt-to976i3o-qPBT6C~pU0QjyMeMgvMVYQ)? If so whats your name in Slack?
