### ISSUE TITLE
Manual Entry doesnt properly update Stats [Bug]

### ISSUE THREAD

**Issue by SalikSayyed** [heylinda/heylinda-app#58]
**Before reporting:**
- [ ] The same bug wasn't already reported, i.e. it's not a duplicate
- [x] This bug is not reported due to an unstable environment

**Steps to reproduce:**

1. Go to Stats
2. Manual Entry on Calender
3. Submit for a day say 18 Aug 23minutes
4. Sumbit for 19Aug 50minutes..
5. The total meditation time should sum upto 73minutes. but it decreases!! to 13minutes.

**Expected behaviour:**
The total meditation time should sum upto 73minutes. but it decreases!! to 13minutes.
**Actual behaviour:**

**Smartphone (please complete the following information):**
 - Device OS android Pie Pixel 3a
**Screenshots/Recording:**
![image](https://user-images.githubusercontent.com/51844798/130837432-25339415-fcc0-4e26-87c3-03f80ec7b1a5.png)
![image](https://user-images.githubusercontent.com/51844798/130837511-bce88399-d1bb-4bc2-b400-3c0a40eaaf4b.png)
![image](https://user-images.githubusercontent.com/51844798/130837552-710fc75e-832c-47cd-8b77-3c273c2d53bb.png)

**Comment by EmersonPinheiro** [comment]
This is still happening, and I think it is actually a bug.
If you, for example, submit 10 minutes for 7 days, the 'Listened' stats will wrongly show '10 minutes'.

**Comment by watadarkstar** [comment]
@EmersonPinheiro Can you open a new bug report and include details on how to reproduce it?
