### ISSUE TITLE
Extending the scope for Cognitive Behaviour Therapy

### ISSUE THREAD

**Issue by kevinfaveri** [heylinda/heylinda-app#8]
I just had this idea I wanted to share. 
It seems like CBT is the kind of therapy (that has a predictive plan of action) that could be mimicked using common computation and improved using something like GPT-3 AI. 
Maybe this app could try something like that.

That said, I would like to help develop this app since meditation played a huge role in the wellbeing of my life.

**Comment by watadarkstar** [comment]
Hey @kevinfaveri nice to e-meet you! That does sound cool. You should join our [Slack](https://join.slack.com/t/heylinda/shared_invite/zt-to976i3o-qPBT6C~pU0QjyMeMgvMVYQ) and post the idea in the ideas channel :)
