### ISSUE TITLE
Upgrade Husky library to latest version

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#87]
Make sure to test the app!

**Comment by YajanaRao** [comment]
Hey @watadarkstar , I see that `pre-commit` hook is missing. Shall I add them as well ?
```json
 "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
```

**Comment by watadarkstar** [comment]
@YajanaRao We already have the pre-commit hook here:
https://github.com/heylinda/heylinda-app/blob/a3db5618696800aa412d3c234eeb698d20ca58a3/.husky/pre-commit#L4-L5

**Comment by pedpess** [comment]
Hi Adrian, I have a PR ready for this here: https://github.com/heylinda/heylinda-app/pull/102, but since @YajanaRao reacted first I would wait a bit. Let me know if any fixes are necessary and I will address these 🙂
